apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
spec:
  selector:
    app: flask-app
  ports:
    - protocol: TCP
      port: 5000  # Port to expose externally
      targetPort: 5000 # Port your Flask app listens on
  type: LoadBalancer  # Exposes the service externally
