apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-app
  template:
    metadata:
      labels:
        app: spring-app
    spec:
      containers:
        - name: spring-app
          image: anu2kool/springapp:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/postgres
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: SPRING_DATASOURCE_PASSWORD
              value: ""
            - name: SPRING_JPA_GENERATE_DDL
              value: "true"
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: update
            - name: SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT
              value: org.hibernate.dialect.PostgreSQLDialect
          volumeMounts:
            - name: logfilevolume
              mountPath: /data
      volumes:
        - name: logfilevolume
          hostPath:
            path: /Users/anukool.dwivedi/Desktop/OnBoardingProject/AppMetaDataValidationService/RegisterPublisher/logs

      imagePullSecrets:
        - name: myregisterykey




