version: "3.8"
services:
  # PostgreSQL service
  db:
    image: postgres:latest
    container_name: my_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ######
      POSTGRES_DB: publisherdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  flaskapp:
    build:
      context: ./flask_app
      dockerfile: Dockerfile
    #network_mode: "host"
    container_name: flaskbundleidapp
    ports:
      - "5000:5000"

  # Spring Boot application service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    #network_mode: "host"
    container_name: main_publisher_app
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/publisherdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: ######



volumes:
  postgres_data:
